
version: 2

models:
    - name: dim_product
      description: "Tabela de dimensão de produtos"
      columns:
          - name: product_sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_customer
      description: "Tabela de dimensão de clientes"
      columns:
          - name: customer_sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
        
    - name: dim_reason
      description: "Tabela de dimensão de motivo de compra"
      columns:
          - name: reason_sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
               
    - name: dim_location
      description: "Tabela de dimensão de localização"
      columns:
          - name: location_sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_employee
      description: "Tabela de dimensão de funcionários"
      columns:
          - name: employee_sk
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: facts_salesorderdetails
      description: "Tabela de fatos de pedidos"
      columns:
          - name: salesorderid
            description: "The primary key for this table"
            tests:
                - unique
                - not_null